import type { NextPage } from 'next'
import Head from 'next/head'
import ReactFullpage from '@fullpage/react-fullpage';
import styles from '../styles/Home.module.css'; // Import css modules stylesheet as styles
import Frame from "../assets/home-frame-photo.svg";
import { motion } from 'framer-motion';



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          <div className={styles.bgWrapper} >
            <Frame className={styles.bg}/>
          </div>

          <ReactFullpage
            //fullpage options
            licenseKey = {'YOUR_KEY_HERE'}
            scrollingSpeed = {1000} /* Options here */

            render={({ state, fullpageApi }) => {
              return (
                <ReactFullpage.Wrapper>
                  <div className={`section ${styles.section}`}>
                    <p className={styles.blackText}>Section 1 (welcome to fullpage.js)</p>
                    <button onClick={() => fullpageApi.moveSectionDown()}>
                      Click me to move down
                    </button>
                  </div>
                  <div className={`section ${styles.section}`}>
                    <motion.div
                      initial={{ opacity: 0 }}
                      whileInView={{ opacity: 1 }}
                      viewport={{ once: false }}
                      transition={{
                        delay: 0.3,
                      }}
                    >
                      <p className={styles.blackText}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

                    </motion.div>
                  </div>
                </ReactFullpage.Wrapper>
              );
            }}
          />


      </main>

    </div>
  )
}

export default Home
